In [1]:
import torch

In [2]:
randomInteger= torch.randint(-100,100,(5,))
print(randomInteger)

tensor([ 69, -92,  90, -30,  40])


In [3]:
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [4]:
tensorZeros= torch.zeros(3,3)
print(tensorZeros)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
ones= torch.ones(4,5)
print(ones)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [6]:
empty =torch.empty(3,2)
print(empty)

tensor([[0.0000e+00, 2.3694e-38],
        [5.3370e-08, 8.1925e-10],
        [8.5011e-07, 4.2498e+21]])


In [7]:
arange = torch.arange(5)
print(arange)

tensor([0, 1, 2, 3, 4])


In [8]:
linspace =torch.linspace(1,10,steps=23)
print(linspace)

tensor([ 1.0000,  1.4091,  1.8182,  2.2273,  2.6364,  3.0455,  3.4545,  3.8636,
         4.2727,  4.6818,  5.0909,  5.5000,  5.9091,  6.3182,  6.7273,  7.1364,
         7.5455,  7.9545,  8.3636,  8.7727,  9.1818,  9.5909, 10.0000])


In [9]:
logspace = torch.logspace(1,10,steps=5)
print(logspace)

tensor([1.0000e+01, 1.7783e+03, 3.1623e+05, 5.6234e+07, 1.0000e+10])


In [10]:
eye =torch.eye(4)
print(eye)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [11]:
emptyLike= torch.empty_like(eye)
print(emptyLike)

tensor([[7.5635e-38, 6.3899e-43, 7.5635e-38, 6.3899e-43],
        [7.5637e-38, 6.3899e-43, 7.5635e-38, 6.3899e-43],
        [7.5635e-38, 6.3899e-43, 7.5635e-38, 6.3899e-43],
        [7.5637e-38, 6.3899e-43, 7.5635e-38, 6.3899e-43]])


In [12]:
#multinomial
probability=torch.tensor([0.05,0.9]);
samples= torch.multinomial(probability,num_samples=10,replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [13]:
#multiplication
tensor1 = torch.zeros(2,2, dtype=torch.int64)
tensor2=torch.ones(2,2, dtype=torch.int64)
tensor3= torch.tensor([[1,2],[3,4]])
print(tensor3 @ tensor2)

tensor([[3, 3],
        [7, 7]])


In [14]:
#concatenation
new=torch.cat((tensor1,tensor2),dim=1)
print(new)

tensor([[0, 0, 1, 1],
        [0, 0, 1, 1]])


In [15]:
#lower triangle matrix
lower= torch.tril(tensor3)
print(lower)

tensor([[1, 0],
        [3, 4]])


In [16]:
#upper triangle matrix
upper = torch.triu(tensor3)
print(upper)

tensor([[1, 2],
        [0, 4]])


In [28]:
out= torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))== 0, float('-inf'))
print(out)

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


In [29]:
exponential = torch.exp(out)
print(exponential)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


TypeError: transpose() received an invalid combination of arguments - got (list), but expected one of:
 * (int dim0, int dim1)
 * (name dim0, name dim1)
